//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cassete_Rentals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cassete_Rentals()
        {
            this.Cassete_Copies = new HashSet<Cassete_Copies>();
        }
    
        public int Order_Id { get; set; }
        public int Copy_Id { get; set; }
        public System.DateTime Give_Date { get; set; }
        public System.DateTime Get_Date { get; set; }
        public int Client_Id { get; set; }
        public int Departament_Id { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Departaments Departaments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cassete_Copies> Cassete_Copies { get; set; }
    }
}
