//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBD.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentalShopEntities : DbContext
    {
        public RentalShopEntities()
            : base("name=RentalShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cassete_Copies> Cassete_Copies { get; set; }
        public virtual DbSet<Cassete_Rentals> Cassete_Rentals { get; set; }
        public virtual DbSet<Cassetes> Cassetes { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Departaments> Departaments { get; set; }
        public virtual DbSet<Film_Groups> Film_Groups { get; set; }
        public virtual DbSet<Generes> Generes { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
